import type { FormatHandler } from "../FormatHandler";

import canvasToBlobHandler from "./canvasToBlob";
import meydaHandler from "./meyda";
import htmlEmbedHandler from "./htmlEmbed";
import FFmpegHandler from "./FFmpeg";
import pdftoimgHandler from "./pdftoimg";
import ImageMagickHandler from "./ImageMagick";
import curaniHandler from "./curani";
import bunburrowsHandler from "./bunburrows";
import svgTraceHandler from "./svgTrace";
import { renameZipHandler, renameTxtHandler } from "./rename";
import envelopeHandler from "./envelope";
import pandocHandler from "./pandoc";
import svgForeignObjectHandler from "./svgForeignObject";
import qoiFuHandler from "./qoi-fu";
import sppdHandler from "./sppd";
import threejsHandler from "./threejs";
import sqlite3Handler from "./sqlite";
import vtfHandler from "./vtf";
import mcMapHandler from "./mcmap";
import jszipHandler from "./jszip";
import alsHandler from "./als";
import qoaFuHandler from "./qoa-fu";
import pyTurtleHandler from "./pyTurtle";
import { fromJsonHandler, toJsonHandler } from "./json";
import nbtHandler from "./nbt";
import peToZipHandler from "./petozip";
import flptojsonHandler from "./flptojson";
import floHandler from "./flo";
import cgbiToPngHandler from "./cgbi-to-png";
import batToExeHandler from "./batToExe";
import textEncodingHandler from "./textEncoding";
import sb3ToHtmlHandler from "./sb3tohtml";
import libopenmptHandler from "./libopenmpt";
import { midiCodecHandler, midiSynthHandler } from "./midi";
import lzhHandler from "./lzh";
import textToGoHandler from "./textToGo";
import txtToInfiniteCraftHandler from "./txtToInfiniteCraft";
import wadHandler from "./wad";
import espeakngHandler from "./espeakng.js"
import textToShellHandler from "./texttoshell";
import batchHandler from "./batch";
import bsorHandler from "./bsor";
import txtToPyHandler from './textToPy';
import fontHandler from "./font";
import icnsHandler from "./icns";
import mcSchematicHandler from "./mcSchematicHandler";
import bsonHandler from "./bson";
import asepriteHandler from "./aseprite";
import csharpHandler from "./csharp";
import n64romHandler from "./n64rom";
import vexflowHandler from "./vexflow";
import toonHandler from "./toon";

const handlers: FormatHandler[] = [];
try { handlers.push(new svgTraceHandler()) } catch (_) { };
try { handlers.push(new canvasToBlobHandler()) } catch (_) { };
try { handlers.push(new meydaHandler()) } catch (_) { };
try { handlers.push(new htmlEmbedHandler()) } catch (_) { };
try { handlers.push(new FFmpegHandler()) } catch (_) { };
try { handlers.push(new pdftoimgHandler()) } catch (_) { };
try { handlers.push(new ImageMagickHandler()) } catch (_) { };
try { handlers.push(new curaniHandler()) } catch (_) { };
try { handlers.push(new bunburrowsHandler()) } catch (_) { };
try { handlers.push(renameZipHandler) } catch (_) { };
try { handlers.push(renameTxtHandler) } catch (_) { };
try { handlers.push(new envelopeHandler()) } catch (_) { };
try { handlers.push(new svgForeignObjectHandler()) } catch (_) { };
try { handlers.push(new qoiFuHandler()) } catch (_) { };
try { handlers.push(new sppdHandler()) } catch (_) { };
try { handlers.push(new threejsHandler()) } catch (_) { };
try { handlers.push(new sqlite3Handler()) } catch (_) { };
try { handlers.push(new vtfHandler()) } catch (_) { };
try { handlers.push(new mcMapHandler()) } catch (_) { };
try { handlers.push(new jszipHandler()) } catch (_) { };
try { handlers.push(new alsHandler()) } catch (_) { };
try { handlers.push(new qoaFuHandler()) } catch (_) { };
try { handlers.push(new pyTurtleHandler()) } catch (_) { };
try { handlers.push(new fromJsonHandler()) } catch (_) { };
try { handlers.push(new toJsonHandler()) } catch (_) { };
try { handlers.push(new nbtHandler()) } catch (_) { };
try { handlers.push(new peToZipHandler()) } catch (_) { };
try { handlers.push(new flptojsonHandler()) } catch (_) { };
try { handlers.push(new floHandler()) } catch (_) { };
try { handlers.push(new cgbiToPngHandler()) } catch (_) { };
try { handlers.push(new batToExeHandler()) } catch (_) { };
try { handlers.push(new sb3ToHtmlHandler()) } catch (_) { };
try { handlers.push(new textEncodingHandler()) } catch (_) { };
try { handlers.push(new libopenmptHandler()) } catch (_) { };
try { handlers.push(new midiCodecHandler()) } catch (_) { };
try { handlers.push(new midiSynthHandler()) } catch (_) { };
try { handlers.push(new lzhHandler()) } catch (_) { };
try { handlers.push(new wadHandler()) } catch (_) { };
try { handlers.push(new pandocHandler()) } catch (_) { };
try { handlers.push(new textToGoHandler()) } catch (_) { };
try { handlers.push(new txtToInfiniteCraftHandler()) } catch (_) { };
try { handlers.push(new espeakngHandler()) } catch (_) { };
try { handlers.push(new textToShellHandler()) } catch (_) { };
try { handlers.push(new batchHandler()) } catch (_) { };
try { handlers.push(new bsorHandler()) } catch (_) { };
try { handlers.push(new txtToPyHandler()) } catch (_) { };
try { handlers.push(new fontHandler()) } catch (_) { };
try { handlers.push(new icnsHandler()) } catch (_) { };
try { handlers.push(new mcSchematicHandler()) } catch (_) { };
try { handlers.push(new bsonHandler()) } catch (_) { };
try { handlers.push(new asepriteHandler()) } catch (_) { };
try { handlers.push(new csharpHandler()) } catch (_) { };
try { handlers.push(new n64romHandler()) } catch (_) { };
try { handlers.push(new vexflowHandler()) } catch (_) { };
try { handlers.push(new toonHandler()) } catch (_) { };

export default handlers;
